### ISSUE TITLE
Disable PDF generation

### ISSUE THREAD

**Issue by emptymalei** [KonradSzwarc/zenith#5]
Thank you @KonradSzwarc for such a nice tool.

**Is your feature request related to a problem? Please describe.**

I have a PDF version of my resume created using LaTeX. I don't need to create a pdf version using zenit.

**Describe the solution you'd like**

Would it be possible to disable the PDF generation and only keep the web versioin?

**Describe alternatives you've considered**

I can ignore the pdf generation but it take effort to maintain both the web version and the pdf version.

**Additional context**

As an example, if I can just disable the pdf generation, I don't need to deal with errors like the following.

```
[og] npm run generate:og exited with code 0
24:01:16 [200] /pdf/ 6ms
[pdf] /Users/leima/git/github/emptymalei/leima/node_modules/puppeteer-core/src/cdp/ExecutionContext.ts:531
[pdf]     throw new Error(
[pdf]           ^
[pdf] 
[pdf] 
[pdf] Error: Execution context was destroyed, most likely because of a navigation.
[pdf]     at rewriteError (/Users/leima/git/github/emptymalei/leima/node_modules/puppeteer-core/src/cdp/ExecutionContext.ts:531:11)
[pdf]     at async ExecutionContext.#evaluate (/Users/leima/git/github/emptymalei/leima/node_modules/puppeteer-core/src/cdp/ExecutionContext.ts:447:7)
[pdf]     at async ExecutionContext.evaluate (/Users/leima/git/github/emptymalei/leima/node_modules/puppeteer-core/src/cdp/ExecutionContext.ts:292:12)
[pdf]     at async IsolatedWorld.evaluate (/Users/leima/git/github/emptymalei/leima/node_modules/puppeteer-core/src/cdp/IsolatedWorld.ts:194:12)
[pdf]     at async CdpFrame.evaluate (/Users/leima/git/github/emptymalei/leima/node_modules/puppeteer-core/src/api/Frame.ts:472:12)
[pdf]     at async CdpPage.evaluate (/Users/leima/git/github/emptymalei/leima/node_modules/puppeteer-core/src/api/Page.ts:2219:12)
[pdf]     at async removeAstroToolbar (/Users/leima/git/github/emptymalei/leima/cli/helpers.ts:79:3)
[pdf]     at async visitPage (/Users/leima/git/github/emptymalei/leima/cli/helpers.ts:69:3)
[pdf]     at async generatePdf (/Users/leima/git/github/emptymalei/leima/cli/commands/pdf.ts:29:3)
[pdf]     at async forAllPages (/Users/leima/git/github/emptymalei/leima/cli/helpers.ts:55:7)
[pdf] 
[pdf] Node.js v20.17.0
[pdf] npm run generate:pdf exited with code 1
file:///Users/leima/git/github/emptymalei/leima/node_modules/execa/lib/return/final-error.js:6
        return new ErrorClass(message, options);
               ^
```

**Comment by KonradSzwarc** [comment]
I think removing the `generate:pdf` command from your `package.json` should solve the problem of automatic PDF creation. If you're sure you won't need PDF generation, you can also delete the `src/pages/pdf` and `src/pdf` directories. Let me know if that solves your issue.

**Comment by emptymalei** [comment]
It worked. Thanks @KonradSzwarc
